# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0.15
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - cellar_network
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

  auth-service:
    networks:
      - cellar_network
    build: .
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_NAME: auth
      DB_HOST: postgres
    ports:
      - 4000:4000

networks:
  cellar_network:
